### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by Strattonoakland** [jesuiscamille/AutoSQLi#22]
root@Dork:~/AutoSQLi# pip install -r requirements.txt 
Requirement already satisfied: pudb in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2019.1)
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (5.6.2)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg (from -r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: urwid>=1.1.1 in /usr/lib/python2.7/dist-packages (from pudb->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: pygments>=1.0 in /usr/lib/python2.7/dist-packages (from pudb->-r requirements.txt (line 1)) (2.3.1)
root@Dork:~/AutoSQLi# ./install.sh 
Could not open requirements file: [Errno 2] No such file or directory: 'WhatWaf/requirements.txt'
Requirement already satisfied: pudb in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (2019.1)
Requirement already satisfied: argparse in /usr/lib/python2.7 (from -r requirements.txt (line 2)) (1.2.1)
Requirement already satisfied: psutil in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (5.6.2)
Requirement already satisfied: requests in /usr/local/lib/python2.7/dist-packages/requests-2.5.0-py2.7.egg (from -r requirements.txt (line 4)) (2.5.0)
Requirement already satisfied: urwid>=1.1.1 in /usr/lib/python2.7/dist-packages (from pudb->-r requirements.txt (line 1)) (2.0.1)
Requirement already satisfied: pygments>=1.0 in /usr/lib/python2.7/dist-packages (from pudb->-r requirements.txt (line 1)) (2.3.1)
Requirement already satisfied: pysocks in /usr/lib/python2.7/dist-packages (1.6.8)

----------------------------
| dependencies installed ! |
----------------------------

running chmod +x on *.py ...
chmod: cannot access 'DorkNet/dorknet.py': No such file or directory
chmod: cannot access 'WhatWaf/whatwaf.py': No such file or directory
chmod: cannot access 'sqlmap/sqlmap.py': No such file or directory
root@Dork:~/AutoSQLi#

**Comment by jesuiscamille** [comment]
Hello ! 

Please delete AutoSQLi's folder, then download it again with submodules enabled:
```
git clone --recursive-submodules git@github.com:jesuiscamille/AutoSQLi.git
```

This will download WhatWaf, sqlmap and other dependencies along AutoSQLi.

Please note that this project is no longer maintained, and most probably broken.
Have a good day !

**Comment by Strattonoakland** [comment]
Hello ! 
Can I white to you in another messenger like WhatsApp or Telegram?

**Comment by jesuiscamille** [comment]
I don't really use any messenger, but you can drop me a mail at [camille.eyries@gmail.com](mailto:camille.eyries@gmail.com) !
